name: Retrain Model

on:
  schedule:
    # Runs at 5:00 UTC every Monday
    - cron: '0 8 1 * *'

jobs:
  train-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Consider increasing timeout
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure compatibility with your script

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: python training_pipeline.py
      env:
        HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}



